apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
secretGenerator:
- name: gitlab-reg-auth
  files:
  - reg-auth.crt
  - reg-auth.key
generatorOptions:
  disableNameSuffixHash: true
