apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docker-registry
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: docker-registry
  serviceName: "docker-registry-svc"
  replicas: 1
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/docker-registry: localhost/nfs-mount-container
      labels:
        app: docker-registry
    spec:
      # securityContext:
      #   runAsUser: 65534
      #   runAsGroup: 65534
      #   fsGroup: 65534
      terminationGracePeriodSeconds: 30
      containers:
      - name: docker-registry
        image: registry:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRY_HTTP_ADDR
          value: "0.0.0.0:5000"
        - name: REGISTRY_HTTP_SECRET
          value: "your-http-secret"
        - name: REGISTRY_HTTP_RELATIVEURLS
          value: "true"
        # Auth
        - name: REGISTRY_AUTH
          value: "token"
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: "http://gitlab-svc/jwt/auth"
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: "container_registry"
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: "gitlab-issuer"
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: "/reg-auth-cert/auth.crt"
        # Storage
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: "/var/lib/registry"
        - name: REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR
          value: "redis"
        # Health
        - name: REGISTRY_HEALTH_STORAGEDRIVER_ENABLED
          value: "true"
        - name: REGISTRY_HEALTH_STORAGEDRIVER_INTERVAL
          value: "10s"
        - name: REGISTRY_HEALTH_STORAGEDRIVER_THRESHOLD
          value: "3"
        # LOG
        # - name: REGISTRY_LOG_LEVEL
        #   value: "debug"
        - name: REGISTRY_LOG_FIELDS_SERVICE
          value: "registry"
        # REDIS
        - name: REGISTRY_REDIS_ADDR
          value: "redis-svc:6379"
        # - name: REGISTRY_REDIS_PASSWORD
        #   value: redispass
        ports:
          - containerPort: 5000
            protocol: TCP
        securityContext:
          capabilities:
            add: 
              - SYS_ADMIN
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 5000
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 5000
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/registry/
          name: data
        - mountPath: /reg-auth-cert
          name: reg-cert
      volumes:
      - name: reg-cert
        secret:
          secretName: gitlab-reg-auth
      - name: data
        persistentVolumeClaim:
          claimName: registry-data-pvc

