apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-notify
  namespace: gitlab
  labels:
    app:  docker-registry
data:
  registry_notifications: |
    - name: registry_endpoint
      url: http://gitlab-svc/notify'
      headers:
        Authorization: ['Yf2_p3iUQYUQbyH-rubPPyP8dpCZkQzA']
      timeout: 500ms
      threshold: 5
      backoff: 1s
