apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: gitlab
spec:
  accessModes:
    # - ReadWriteOnce
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: registry-data-storage
