---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-svc
  namespace: gitlab
  labels:
    app: docker-registry
spec:
  selector:
    app: docker-registry
  ports:
    - name: http-web
      protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: ClusterIP
