apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab # has to match .spec.template.metadata.labels
  serviceName: "gitlab-svc"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: gitlab # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      # securityContext:
      #   fsGroup: 998
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:14.4.2-ce.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-web
              containerPort: 80
            - name: tcp-ssh
              containerPort: 32222
            - name: http-reg
              containerPort: 5005
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: gitlab-omnibus
                  key: gitlab_omnibus_config
          # livenessProbe:
          #   httpGet:
          #     path: /help
          #     port: http
          #   # This pod takes a very long time to start up. Be cautious when
          #   # lowering this value to avoid Pod death during startup.
          #   initialDelaySeconds: 200
          #   timeoutSeconds: 15
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 10
          # readinessProbe:
          #   httpGet:
          #     path: /help
          #     port: http-web
          #   initialDelaySeconds: 60
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          # resources:
          #   limits:
          #     memory: 3000Mi
          #     # cpu: 800m
          #   requests:
          #     memory: 2000Mi
          #     # cpu: 600m
          volumeMounts:
            - name: reg-cert
              mountPath: /reg-auth-cert
            - name: gitlab-data
              mountPath: /var/opt/gitlab
      volumes:
        - name: reg-cert
          secret:
            secretName: gitlab-reg-auth
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data-pvc
