apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ing
  namespace: gitlab
  labels:
    app: gitlab
  annotations:
    # создает .key автоматически
    # cert-manager.io/cluster-issuer: selfsigned-issuer
    # cert-manager.io/issuer: gitlab-ca-issuer
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    kubernetes.io/ingress.class: traefik

spec:
  rules:
  - host: gitlab.dev-srv.home.lan
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gitlab-svc
            port:
              number: 80
  - host: reg.dev-srv.home.lan
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gitlab-svc
            port:
              number: 5005
  tls:
    - hosts:
        - "gitlab.dev-srv.home.lan"
        - "reg.dev-srv.home.lan"
      secretName: root-secret
