apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-ing
  namespace: gitlab
  labels:
    app: gitlab
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitlab.server.lan`) && (PathPrefix(`/`))
      kind: Rule
      services:
        - name: gitlab-svc
          namespace: gitlab
          kind: Service
          port: 80
      # middlewares:
      #   - name: https-redirectscheme
      #     namespace: gitlab
    - match: Host(`pages.server.lan`) && (PathPrefix(`/`))
      kind: Rule
      services:
        - name: gitlab-svc
          namespace: gitlab
          kind: Service
          port: 8090
    - match: Host(`reg.gitlab.server.lan`) && (PathPrefix(`/`))
      kind: Rule
      services:
        - name: docker-registry-svc
          namespace: gitlab
          kind: Service
          port: 5000
      # middlewares:
      #   - name: https-redirectscheme
      #     namespace: gitlab
  tls:
    secretName: root-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitlab-ssh-ing
  namespace: gitlab
spec:
  entryPoints:
    - ssh-gitlab
  routes:
  - match: HostSNI(`*`)
    services:
    - name: gitlab-ssh-svc
      namespace: gitlab
      port: 32222

# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: gitlab-http-pages
# spec:
#   entryPoints:
#     - http
#   routes:
#   - match: HostRegexp(`{subdomain:[a-z]+}.pages.rudenspavasaris.id.lv`) # or {subdomain:.*}
#     priority: 1001
#     kind: Rule
#     services:
#     - name: gitlab
#       port: 80
