apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-ing
  namespace: gitlab
  labels:
    app: gitlab
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitlab.server.lan`) && (PathPrefix(`/`))
      kind: Rule
      services:
        - name: gitlab-svc
          namespace: gitlab
          kind: Service
          port: 80
      # middlewares:
      #   - name: https-redirectscheme
      #     namespace: gitlab
    - match: Host(`pages.gitlab.server.lan`) && (PathPrefix(`/`))
      kind: Rule
      services:
        - name: gitlab-svc
          namespace: gitlab
          kind: Service
          port: 8090
    - match: Host(`reg.gitlab.server.lan`) && (PathPrefix(`/`))
      kind: Rule
      services:
        - name: docker-registry-svc
          namespace: gitlab
          kind: Service
          port: 5000
      # middlewares:
      #   - name: https-redirectscheme
      #     namespace: gitlab
  tls:
    secretName: root-secret
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRouteTCP
# metadata:
#   name: gitlab-ssh-ing
# spec:
#   entryPoints:
#     - ssh
#   routes:
#   - match: HostSNI(`gitlab.dev-srv.home.lan`)
#     services:
#     - name: gitlab-ssh-svc
#       port: 22
