apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-etc-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
  volumeName: gitlab-etc-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-git-data-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
  volumeName: gitlab-git-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-uploads-data-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
  volumeName: gitlab-uploads-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-shared-data-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
  volumeName: gitlab-shared-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-builds-data-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
  volumeName: gitlab-builds-data-pv
