apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-selfsigned-ca
  namespace: gitlab
spec:
  commonName: gitlab-selfsigned-ca
  secretName: root-secret
  duration: 2880h # 2880h(120d)
  renewBefore: 30m # 360h(15d)
  isCA: true
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  subject:
    countries: [RU]
    organizations: [XAOC Co]
    organizationalUnits: [DevOps, Gitlab]
  usages:
    - server auth
    - client auth
  dnsNames:
    - gitlab.server.lan
    - pages.server.lan
    - reg.gitlab.server.lan
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gitlab-ca-issuer
  namespace: gitlab
spec:
  ca:
    secretName: root-secret
