apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: postgresql # has to match .spec.template.metadata.labels
  serviceName: "postgresql-svc"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: postgresql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      # securityContext:
      #   fsGroup: 998
      containers:
      - name: postgresql
        image: postgres:12-alpine
        ports:
          - containerPort: 5432
            name: postgres
        env:
          - name: POSTGRES_USER
            value: gitlab
          - name: POSTGRES_DB
            value: gitlab_home_dev
          - name: POSTGRES_PASSWORD
            value: gitlab
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
