apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: postgresql # has to match .spec.template.metadata.labels
  serviceName: "postgresql-svc"
  replicas: 1 # by default is 1
  template:
    metadata:
      # annotations:
      #   container.apparmor.security.beta.kubernetes.io/postgresql: localhost/nfs-mount-container
      labels:
        app: postgresql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      # securityContext:
      #   runAsUser: 70
      #   # runAsGroup: 1000
      #   fsGroup: 70
      containers:
      - name: postgresql
        image: postgres:12-alpine
        ports:
          - containerPort: 5432
            name: postgres
        env:
          - name: POSTGRES_USER
            value: gitlab
          - name: POSTGRES_DB
            value: gitlab_home_dev
          - name: POSTGRES_PASSWORD
            value: gitlab
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        # securityContext:
        #   capabilities:
        #     add: 
        #       - SYS_ADMIN
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 20
        volumeMounts:
          - name: postgres-data
            # subPath: pgdata
            mountPath: /var/lib/postgresql/data
            readOnly: false
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
