# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: postgres-data-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-data-pv
#   namespace: gitlab
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: postgres-data-storage
#   local:
#     path: /mnt/data_store/gitlab/postgres_data
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - dev-srv # имя НОДЫ а не пода
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
  namespace: gitlab
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-data-storage
  nfs:
    server: 10.43.85.189
    path: "/gitlab/postgres_data"
  mountOptions:
    - nfsvers=4
  persistentVolumeReclaimPolicy: Retain