apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: gitlab
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - image: redis:6.2-rc3-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          securityContext:
            capabilities:
              add: 
                - SYS_ADMIN
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 200m
          volumeMounts:
            - name: redis
              mountPath: /var/lib/redis
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis-pvc
