apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: gitlab
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      # annotations:
      #   container.apparmor.security.beta.kubernetes.io/redis: localhost/nfs-mount-container
      labels:
        app: redis
    spec:
      # securityContext:
      #   runAsUser: 65534
      #   runAsGroup: 65534
      #   fsGroup: 65534
      containers:
        - image: redis:alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          # securityContext:
            # capabilities:
            #   add: 
            #     - SYS_ADMIN
          env:
            - name: REDIS_REPLICATION_MODE
              value: master
          resources:
            requests:
              memory: 50Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 500m
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          volumeMounts:
            - name: redis
              mountPath: /data
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis-pvc
